### ISSUE TITLE
netstandard versions

### ISSUE THREAD

**Issue by burakoner** [farukterzioglu/HDWallet#36]
Merhaba
netstandard versiyonunu planlıyor musunuz?

**Comment by farukterzioglu** [comment]
Merhabalar, planimda yok.

**Comment by farukterzioglu** [comment]
@burakoner netstandart versiyonlarini RC-1 olarak yayinladim. 
Detayli testler sonrasinda normal versiyonlarini da cikarim.
Tron icin hazir ; https://www.nuget.org/packages/HDWallet.Tron/0.5.0

**Comment by burakoner** [comment]
Teşekkür ederim emeklerin için. Hemen inceliyorum
