### ISSUE TITLE
Balance and transactions

### ISSUE THREAD

**Issue by sinaptech** [farukterzioglu/HDWallet#43]
Hello. Thank you for sharing this project. I have some questions

After creating hd wallet of tron and generate some address on it how to get the balance and transactions of that address?

May you please help me hot to get a webhook data when new deposit on network for the generated address take place?

**Comment by farukterzioglu** [comment]
Hi, you welcome

Balance and transaction queries can not be send with this project. 
You need to send http requests to a Tron node, like TronGrid or if there is any, you need to use some indexer services (paid or free) to get that information.

For example to get the balance for an address;
```
curl --location --request POST 'https://api.trongrid.io/walletsolidity/getaccount' \
--header 'Content-Type: application/json' \
--data-raw '{
    "address": "TSFa2......",
    "visible": true
}'
```

You can't get transactions of an address from node directly. You need to scan the blockchain block by block, transaction by transaction to check it that address received a transaction. 
Or you can use an existing indexer service if you find any, I don't know any.

**Comment by sinaptech** [comment]
@farukterzioglu thanks. and also for transfering trx or trc20 token I should use other APIs?

**Comment by farukterzioglu** [comment]
TRX transfer kinda easy, you can check here;
https://github.com/farukterzioglu/HDWallet/tree/master/src/HDWallet.Tron

But transferring TRC20 requires more stuff also regarding to Ethereum, you can start to read Tron docs for this.

**Comment by sinaptech** [comment]
@farukterzioglu  thanks
