### ISSUE TITLE
Deposit USDT TRC20

### ISSUE THREAD

**Issue by sinaptech** [farukterzioglu/HDWallet#58]
Hello. I have created 3 address from account 0 of Tron HD Wallet. Now the question is can I deposit usdt trc20 to these 3 addresses? or first must deposit some trx to every address? I want to get every user in my website one address to deposit usdt trc20 without need to deposit trx first. Can I do this?

**Comment by farukterzioglu** [comment]
Hi, 
Yes you can do that. However, whenever you want to use those usdt trc20 balances, you will need TRX on those addresses.
User doesn't need to send TRX, you will need to send TRX when you want to spend usdts on any address
