### ISSUE TITLE
Internal Address

### ISSUE THREAD

**Issue by sinaptech** [farukterzioglu/HDWallet#59]
Hello. What is internal address in hd wallet of tron for? What is the diference between address 0 of account 0 of an mnemonic in deposit and internal mode?

**Comment by farukterzioglu** [comment]
Internal addresses are no different than external addresses (deposits) in technical point of view. 
They just serve to different purpose.
Kindly check the explanation in BIP32 doc;
https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
 
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/476514/162159876-a5c8e703-9a2a-4d8e-af2e-4577caa92c83.png">
